name: Test Streamlit App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install pandas streamlit

      - name: Check Python files syntax
        run: |
          python -m py_compile app.py